import { ContentLayout } from '@/components/layout/ContentLayout';
import { AlertTriangle, TrendingDown, Clock, ShieldAlert } from 'lucide-react';
import { useLanguage } from '@/contexts/LanguageContext';

export const RiskPage = () => {
  const { locale } = useLanguage();
  return (
    <ContentLayout 
      title={locale === 'zh' ? '风险框架' : 'Risk Framework'} 
      subtitle={locale === 'zh' ? 'USD.萌 的综合风险分析、缓解技术与协议参数。' : 'Comprehensive risk analysis, mitigation techniques, and parameters for USDM.'}
    >
      <div className="space-y-12">
        <section>
          <h2>{locale === 'zh' ? '协议风险简介' : 'Introduction to Protocol Risks'}</h2>
          <p>
            {locale === 'zh' ? '去中心化金融（DeFi）协议涉及固有的风险。在 USD.萌，透明度是我们的最高优先事项。我们希望所有用户，无论是散户还是机构，都能准确理解协议在极端市场条件（包括黑天鹅事件）下的运作方式。' : 'Decentralized finance (DeFi) protocols involve inherent risks. At USDM, transparency is our highest priority. We want all users, whether retail or institutional, to understand exactly how the protocol behaves under extreme market conditions, including black swan events.'}
          </p>
          <div className="p-6 bg-red-500/10 border border-red-500/20 rounded-xl mt-6 flex items-start gap-4">
            <AlertTriangle className="w-8 h-8 text-red-500 flex-shrink-0 mt-1" />
            <div>
              <h3 className="text-xl font-bold text-red-500 m-0 mb-2">{locale === 'zh' ? '重要通知' : 'Notice'}</h3>
              <p className="m-0 text-text-secondary text-sm">
                {locale === 'zh' ? '没有哪个 DeFi 协议是绝对没有风险的。请不要投入您无法承受损失的资金。在参与之前，请务必进行充分的研究（DYOR）并查看我们的智能合约。' : 'No DeFi protocol is entirely risk-free. Please do not supply capital you cannot afford to lose. Always perform your own research and review our smart contracts.'}
              </p>
            </div>
          </div>
        </section>

        <section>
          <h2>{locale === 'zh' ? '主要风险向量' : 'Key Risk Vectors'}</h2>
          
          <div className="grid gap-6 mt-8">
            <div className="p-6 bg-surface border border-border rounded-xl">
              <div className="flex items-center gap-3 mb-4">
                <TrendingDown className="w-6 h-6 text-primary" />
                <h3 className="text-xl font-bold m-0">{locale === 'zh' ? '资金费率风险 (Funding Rate Risk)' : 'Funding Rate Risk'}</h3>
              </div>
              <p className="text-text-muted text-sm m-0">
                {locale === 'zh' ? 'USD.萌 依赖 Delta 中性头寸来维持其锚定。如果永续合约交易所的资金费率大幅转负并长时间保持该状态，USD.萌 产生的收益可能会降低，甚至可能需要动用协议的保险基金（Insurance Fund）来维持锚定。' : 'USDM relies on delta-neutral positions to maintain its peg. If funding rates on perpetual exchanges turn deeply negative and remain there for extended periods, the yield generated by USDM may decrease, potentially requiring the protocol to utilize its insurance fund to maintain the peg.'}
              </p>
            </div>

            <div className="p-6 bg-surface border border-border rounded-xl">
              <div className="flex items-center gap-3 mb-4">
                <ShieldAlert className="w-6 h-6 text-primary" />
                <h3 className="text-xl font-bold m-0">{locale === 'zh' ? '智能合约风险 (Smart Contract Risk)' : 'Smart Contract Risk'}</h3>
              </div>
              <p className="text-text-muted text-sm m-0">
                {locale === 'zh' ? '虽然我们的合约经过了多重严格审计且实行 24/7 监控，但在核心逻辑中，或在 USD.萌 部署资金的去中心化交易所（如 Uniswap 或 GMX）中，始终存在非零的漏洞或黑客攻击风险。' : 'While our contracts are heavily audited and monitored 24/7, there is always a non-zero chance of an exploit or vulnerability in the core logic, or in the decentralized exchanges (like Uniswap or GMX) where USDM deploys capital.'}
              </p>
            </div>

            <div className="p-6 bg-surface border border-border rounded-xl">
              <div className="flex items-center gap-3 mb-4">
                <Clock className="w-6 h-6 text-primary" />
                <h3 className="text-xl font-bold m-0">{locale === 'zh' ? '流动性与赎回风险 (Liquidity & Redemption Risk)' : 'Liquidity & Redemption Risk'}</h3>
              </div>
              <p className="text-text-muted text-sm m-0">
                {locale === 'zh' ? '在极端市场波动期间，如果链上流动性受限，提款队列可能会出现延迟。协议通过维持强大的闲置稳定币（USDC/USDT）缓冲池来处理即时赎回，以此缓解这一风险。' : 'During times of extreme market volatility, withdrawal queues might experience delays if on-chain liquidity is constrained. The protocol mitigates this by maintaining a robust buffer of idle stablecoins (USDC/USDT) to handle immediate redemptions.'}
              </p>
            </div>
          </div>
        </section>

        <section>
          <h2>{locale === 'zh' ? '缓解策略 (Mitigation Strategies)' : 'Mitigation Strategies'}</h2>
          <p>
            {locale === 'zh' ? '为了应对这些风险向量，USD.萌 实施了多层防御机制：' : 'To address these vectors, USDM implements several layers of defense:'}
          </p>
          <ul className="space-y-4">
            <li>
              <strong>{locale === 'zh' ? '保险基金 (Insurance Fund)：' : 'Insurance Fund:'}</strong> {locale === 'zh' ? '一个专门由协议拥有的流动性池（POL），专门设计用于覆盖负资金费率时期并保护 sUSD.萌 收益。' : 'A dedicated pool of protocol-owned liquidity explicitly designed to cover negative funding rate periods.'}
            </li>
            <li>
              <strong>{locale === 'zh' ? '熔断机制 (Circuit Breakers)：' : 'Circuit Breakers:'}</strong> {locale === 'zh' ? '如果预言机偏差超过 2% 或检测到异常的交易模式，将自动暂停铸造和销毁功能。' : 'Automated pauses on minting and burning if oracle deviations exceed 2% or if anomalous transaction patterns are detected.'}
            </li>
            <li>
              <strong>{locale === 'zh' ? '多元化部署 (Diversified Venues)：' : 'Diversified Venues:'}</strong> {locale === 'zh' ? '协议资本分散在多个顶级交易所中，以防止单点故障（SPOF）。' : 'Protocol capital is spread across multiple top-tier exchanges to prevent a single point of failure.'}
            </li>
          </ul>
        </section>
      </div>
    </ContentLayout>
  );
};