import { ContentLayout } from '@/components/layout/ContentLayout';

export const WhitepaperPage = () => {
  return (
    <ContentLayout 
      title="Whitepaper" 
      subtitle="A Decentralized, Yield-Bearing Stablecoin Powered by Delta-Neutral Strategies"
    >
      <div className="space-y-12">
        <section>
          <h2>Abstract</h2>
          <p>
            The USDM protocol introduces a novel architecture for stablecoin issuance. By combining 
            overcollateralization with delta-neutral hedging strategies, USDM provides a fully 
            decentralized, price-stable asset that automatically accrues yield. This paper outlines 
            the mechanism design, tokenomics, and risk mitigation strategies that form the core of 
            the protocol.
          </p>
        </section>

        <section>
          <h2>1. Introduction</h2>
          <p>
            Fiat-backed stablecoins suffer from centralization risk and regulatory uncertainty. 
            Algorithmic stablecoins have repeatedly failed to maintain their peg under market stress. 
            USDM solves these trilemmas by implementing a strategy that pairs spot crypto collateral 
            with equivalent short positions in perpetual futures markets.
          </p>
          <div className="bg-surface border border-border p-6 rounded-lg mt-6">
            <h3 className="text-xl font-bold mb-4">Core Principles</h3>
            <ol className="list-decimal pl-6 space-y-2">
              <li><strong>Capital Efficiency:</strong> Near 1:1 collateralization ratio.</li>
              <li><strong>Censorship Resistance:</strong> No reliance on traditional banking infrastructure.</li>
              <li><strong>Value Accrual:</strong> Funding rates from perpetual markets flow directly to holders.</li>
            </ol>
          </div>
        </section>

        <section>
          <h2>2. The Delta-Neutral Mechanism</h2>
          <p>
            When a user deposits collateral (e.g., stETH) to mint USDM, the protocol simultaneously 
            opens a 1x short position on a decentralized perpetual exchange (e.g., GMX or Synthetix). 
            This ensures that regardless of the underlying asset's price movement, the total USD 
            value of the position remains constant.
          </p>
          <div className="bg-gradient-to-br from-primary/10 to-secondary/10 p-6 rounded-xl border border-primary/20 my-8">
            <h4 className="text-primary mt-0 mb-4">Mathematical Model</h4>
            <div className="font-mono text-sm space-y-2">
              <p>V_total = V_collateral + V_short</p>
              <p>ΔV_total = ΔV_collateral + ΔV_short</p>
              <p>Since ΔV_short = -ΔV_collateral</p>
              <p>ΔV_total = 0</p>
            </div>
          </div>
        </section>

        <section>
          <h2>3. Yield Generation</h2>
          <p>
            The yield generated by USDM is derived from two primary sources:
          </p>
          <ul>
            <li>
              <strong>Funding Rates:</strong> Historically, crypto perpetual markets exhibit a positive funding 
              rate bias, meaning long positions pay short positions.
            </li>
            <li>
              <strong>Staking Yields:</strong> The underlying collateral (like stETH) continues to accrue 
              staking rewards natively.
            </li>
          </ul>
        </section>

        <section>
          <h2>4. Conclusion</h2>
          <p>
            USDM represents the next evolution in decentralized money. By separating the store of value 
            from volatile market movements while capturing the structural premiums of crypto markets, 
            it provides a robust foundation for the future of decentralized finance.
          </p>
        </section>
      </div>
    </ContentLayout>
  );
};
